FROM node:22-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --shamefully-hoist --ignore-scripts --fetch-timeout 300000

EXPOSE 3000
ENV PNPM_VERIFY_DEPS_BEFORE_RUN=false
CMD ["node", "node_modules/next/dist/bin/next", "dev"]
