FROM node:22-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --shamefully-hoist

COPY prisma ./prisma
RUN DATABASE_URL="postgresql://user:pass@localhost:5432/db" pnpm db:generate

EXPOSE 3000
CMD ["pnpm", "dev"]
